### ISSUE TITLE
Create Community - Tags are not saved.

### ISSUE THREAD

**Issue by emregurer** [BogaziciUniversitySWEG1/web-app-repo#105]

**Comment by alperkaratepe** [comment]
CreateCommunityTag:
URL: /api/tags/communityTags/{communityId}
Method: POST
Input: Collection of Tag
Output: boolean
Request example:
[
  {
    "tag": "Iphone",
    "semantic": "Smart Phone"
  },
    {
    "tag": "Samsung",
    "semantic": "Smart Phone"
  },
    {
    "tag": "HP",
    "semantic": "Notebook"
  }
  ]

**Comment by alperkaratepe** [comment]
getCommunityTags:
URL: /api/tags/communityTags/{communityId}
Method: GET
Input: empty
Output: Colelction of Tags
Example Response:
[
  {
    "tagId": 1,
    "creationDate": 1449913644000,
    "tag": "Java",
    "semantic": "Programming Language"
  },
  {
    "tagId": 3,
    "creationDate": 1449913644000,
    "tag": "Python",
    "semantic": "Programming Language"
  },
  {
    "tagId": 5,
    "creationDate": null,
    "tag": "Android",
    "semantic": "Programming Language"
  }
]

**Comment by emregurer** [comment]
fixed
