### ISSUE TITLE
General Security - session control should be implemented

### ISSUE THREAD

**Issue by serkankaracay** [BogaziciUniversitySWEG1/web-app-repo#148]
we can use UUID(); in my sql such that

1- user logins. An unique identifier is assigned to the user such as '6ccd780c-baba-1026-9564-0040f4311e29'. Also a flag for being online is set for this user. ie: IsOnline=1

2- this unique identifier is used on the html pages for uid such as "communityrequests.html?cid=1&uid=6ccd780c-baba-1026-9564-0040f4311e29

3- In every page which online users can see, this uid is sent to db and if the uid is online, it is ok. If the uid is not online, then the user is sent to the index page and warning is shown.

4- For every log in and log out operations, the uid is removed from db and recreated.

**Comment by emregurer** [comment]
cancelled.
