### ISSUE TITLE
Popular Community Tags are not working

### ISSUE THREAD

**Issue by emredmrl** [BogaziciUniversitySWEG1/web-app-repo#157]
"Popular community tags" link is not functioning as it should. It does not return anything.

**Comment by emredmrl** [comment]
Added a web service end point. It uses GET method. The url is 

http://localhost:8080/api/communities/tagcount

Return data sample is like:
`
[
  {
    "tagName": "js",
    "tagCount": 1
  },
  {
    "tagName": "javascript",
    "tagCount": 1
  },
  {
    "tagName": "data model",
    "tagCount": 1
  },
  {
    "tagName": "content",
    "tagCount": 1
  }
]
`

**Comment by emregurer** [comment]
fixed.
