### ISSUE TITLE
Index - BuCOMP button

### ISSUE THREAD

**Issue by hasancanakgunduz** [BogaziciUniversitySWEG1/web-app-repo#173]
Bug Name: Pushing BuCOMP button more than once in short time causes error dialog to show up.
Build Number: Build taken on 20 Dec 2015, 17:09
Severity: Low
Priority: Low
Environment: Google Chrome / Mac OSX

Steps To Reproduce:
1) Open http://localhost:8080/index.html
2) Click on BuCOMP button two or three times quickly.

Expected result: Page should be loaded without any error dialog.

**Comment by serkankaracay** [comment]
not a bug.  Pushing BuCOMP button more than once in short time causes calling webservice, and the web service return error .
