### ISSUE TITLE
Register - Warning Dialogs

### ISSUE THREAD

**Issue by hasancanakgunduz** [BogaziciUniversitySWEG1/web-app-repo#175]
Enhancement Name: Warning dialogs is not compatible with the one in index page.
Build Number: Build taken on 20 Dec 2015, 17:09
Severity: Low
Priority: Low
Environment: Google Chrome / Mac OSX

Steps To Reproduce:
1) Open http://localhost:8080/register.html
2) Keep name field blank
3) Click on save

Expected result: Warning dialog's design should be same with the one in index page.

**Comment by serkankaracay** [comment]
gui_helper.alert is used.
