### ISSUE TITLE
Index - Enter button for login

### ISSUE THREAD

**Issue by hasancanakgunduz** [BogaziciUniversitySWEG1/web-app-repo#178]
Enhancement Name: After user enters password, if he hits enter key login process should start.
Build Number: Build taken on 22 Dec 2015, 14:03
Severity: Low
Priority: Low
Environment: Google Chrome / Mac OSX

Steps To Reproduce:
1- Enter email
2- Enter pasword
3- Hit enter

Expected result: Login process should start.

**Comment by emregurer** [comment]
fixed.
