### ISSUE TITLE
Createcommunity - Community can not be created

### ISSUE THREAD

**Issue by hasancanakgunduz** [BogaziciUniversitySWEG1/web-app-repo#183]
Bug Name: Community can not be created
Build Number: Build taken on 22 Dec 2015, 14:03
Severity: High
Priority: High
Environment: Google Chrome / Mac OSX

Steps To Reproduce:
1- Login to application
2- Click on Create Community
3- Enter below data:
Title: iOS Developers
Description: Talk about new trends in iOS Development.
Tags: iOS and mobile
Visibility: Public
Requires Approval: No
Rest of the options are All Joined Members
Invited Members. akgunduzh@gmail.com

Expected result: And informative message should popup for succesfull comunity creation notice.

**Comment by emregurer** [comment]
closed
