### ISSUE TITLE
Community - Member profile photos

### ISSUE THREAD

**Issue by hasancanakgunduz** [BogaziciUniversitySWEG1/web-app-repo#187]
Bug Name: Member profile photos are not observed in community detail page.
Build Number: Build taken on 22 Dec 2015, 14:03
Severity: Medium
Priority: Medium
Environment: Google Chrome / Mac OSX

Steps To Reproduce:
1- Go to http://localhost:8080/community.html?cid=32&uid=31

Expected result: Member photos should be displayed at the bottom of the page.

**Comment by serkankaracay** [comment]
user pictures should be uploaded after getting last version of project
