### ISSUE TITLE
Community - Resource list window

### ISSUE THREAD

**Issue by hasancanakgunduz** [BogaziciUniversitySWEG1/web-app-repo#197]
Bug Name: Resource list window's design is not compatible with design, also profile photo of the resource adder is not displayed.
Build Number: Build taken on 22 Dec 2015, 14:03
Severity: Medium
Priority: Medium
Environment: Google Chrome / Mac OSX

Steps To Reproduce:
1- Go to http://localhost:8080/community.html?cid=32&uid=31
2- Click on see all for resource list.

Expected result: Resources should be displayed.

**Comment by serkankaracay** [comment]
file donwload links are fixed
