### ISSUE TITLE
Community - Upcoming events

### ISSUE THREAD

**Issue by hasancanakgunduz** [BogaziciUniversitySWEG1/web-app-repo#198]
Bug Name: Past meetings are displayed on upcoming events section.
Build Number: Build taken on 22 Dec 2015, 14:03
Severity: Medium
Priority: Medium
Environment: Google Chrome / Mac OSX

Steps To Reproduce:
1- Go to http://localhost:8080/community.html?cid=32&uid=31

Expected result: Observe that there is an event with 21 December date seen as upcoming event. Today's date is 23 December so it should not be seen there.

**Comment by serkankaracay** [comment]
meetings those will be start in 24 hours are listed at upcoming events.
