### ISSUE TITLE
Communityrequests - Warning dialog

### ISSUE THREAD

**Issue by hasancanakgunduz** [BogaziciUniversitySWEG1/web-app-repo#212]
Bug Name: If there is no request, the warning dialog UI should be compatible with the one in index page.
Build Number: Build taken on 27 Dec 2015, 16:44
Severity: Low
Priority: Low
Environment: Google Chrome / Mac OSX

Steps To Reproduce:
1- Open http://localhost:8080/communityrequests.html?uid=31&cid=32

Expected result: ;The warning dialog UI should be compatible with the one in index page.

**Comment by serkankaracay** [comment]
alert, info and warning boxes are jeasy-ui boxes. "swal" method was used in index, I changed it. GUI_HELPER.ALERT function should be used in all pages...
