### ISSUE TITLE
Implement semantic tagging services

### ISSUE THREAD

**Issue by alperkaratepe** [BogaziciUniversitySWEG1/web-app-repo#44]

**Comment by alperkaratepe** [comment]
Available APIs: http://www.programmableweb.com/category/semantics/apis?category=20377
Some of them:
- meaningcloud, https://www.meaningcloud.com
- Amplify, http://www.programmableweb.com/api/amplify
- Extractiv, http://extractiv.com/
- b-semantic, http://b-semantic.elasticbeanstalk.com/public/#/home

**Comment by emredmrl** [comment]
We are using dbpedia lookup in local server. This service makes a keyword search and suggests related keywords, categories as output.
