### ISSUE TITLE
Create Topic Service Method

### ISSUE THREAD

**Issue by emregurer** [BogaziciUniversitySWEG1/web-app-repo#45]
A method for creating a topic of a community.
Service Parameters:
- Title
- Description
- Community
  - CommunityId

Returns:
Id of the created topic. If the action is invalid, it will return -1.

**Comment by alperkaratepe** [comment]
URL: /api/topics
Method: POST
Input: Topic object (JSON)
Output: Topic Object (JSON with topic id)
