### ISSUE TITLE
Topic List of a Community Service Method

### ISSUE THREAD

**Issue by emregurer** [BogaziciUniversitySWEG1/web-app-repo#46]
A method to list the topics of a community
Input parameters:
- Community
  - CommunityId

Output Parameters:
- Topic
  - TopicId
  - Title
  - Description
  - TagList[]
    - TagId
    - Tag
    - CreationDate

**Comment by alperkaratepe** [comment]
URL: /api/topics/communityTopics/{communityId}
Method: GET
Response: List of Topics
Request Example: http://localhost:8080/api/topics/communityTopics/1
Response example:
[
  {
    "topicId": 1,
    "description": "This is the description of my new topic",
    "communityId": 1,
    "title": "My new topic title"
  },
  {
    "topicId": 2,
    "description": "This is the description of my second new topic",
    "communityId": 1,
    "title": "My second new topic title"
  }
]
