### ISSUE TITLE
Topic Detail Service Method

### ISSUE THREAD

**Issue by emregurer** [BogaziciUniversitySWEG1/web-app-repo#47]
A method to get detailed information of the topic.
Service Parameters:
- TopicId

Output Parameters:
- Topic
  - TopicId
  - Title
  - Description
  - TagList[]
    - TagId
    - Tag
    - CreationDate
  - Posts[]
    - PostId
    - User
    - Title
    - Post
    - PostDate

**Comment by alperkaratepe** [comment]
getTopicById method added.
URL: /api/topics/{id} - id=topicId
Method: GET
Return: Topic object
