### ISSUE TITLE
Create Post Service Method

### ISSUE THREAD

**Issue by emregurer** [BogaziciUniversitySWEG1/web-app-repo#48]
A method for creating a post
Service Parameters:
- User
  - UserId
- Title
- Post
- PostDate

Return Parameter:
- PostId

**Comment by alperkaratepe** [comment]
Emre, what about associatedobjectid, I think it should also exist in inputs?

**Comment by alperkaratepe** [comment]
It will be better to send Post object in JSON format as input.

**Comment by alperkaratepe** [comment]
URL: http://localhost:8080/api/posts
Method: POST
Input example (JSON): 
{
  "associatedObjectId": 1,
  "post": "This is the content of my first post",
  "postDate": 1449232561000,
  "title": "My First Post",
  "postTypeId": 1,
  "userId": 1
}
