### ISSUE TITLE
Community Join Request Service Method

### ISSUE THREAD

**Issue by emregurer** [BogaziciUniversitySWEG1/web-app-repo#49]
A method for community join request
Service parameters:
- Community
  - CommunityId
- User
  - UserId
- RequestDate

Output Parameter:
Result of the operation (true/false)

**Comment by alperkaratepe** [comment]
URL: /api/communityRequests
getAllCommunityRequests(): If you make a GET request you get the list of communityrequests.
joinCommunity(userId, communityId): If you make a POST request with communityId and userId parameters, a new CommunityRequest row created in communityrequests table. If successfully executed, returns true, else false.
