### ISSUE TITLE
Community Join Service Method

### ISSUE THREAD

**Issue by emregurer** [BogaziciUniversitySWEG1/web-app-repo#50]
A method for joining the community. The method will insert data to the CommunityMembers table.
Service Parameters:
- Community
  - CommunityId
- User
  - UserId

Output parameter:
- Result of the operation (true/false)

Note: The value of the RoleId column will be the value of communityMember role.

**Comment by alperkaratepe** [comment]
I think this is the approve community request service, right?

NO, this is different from approve community request, approve will additionaly update communityrequest table.

**Comment by alperkaratepe** [comment]
getCommunityMembers (/api/communityMembers/{communityId} - GET) and 
addCommunityMember (/api/communityMembers - POST - params:userId, communityId, roleId) methods added into service api. addCommunity method returns true if a new row is successfully inserted into communitymembers table.

NOTE: roleId parameter in post params should exist in roles table (you can manually insert a new row)
