### ISSUE TITLE
Create Meeting Service Implementation

### ISSUE THREAD

**Issue by hasancanakgunduz** [BogaziciUniversitySWEG1/web-app-repo#62]
Parameters:
userId: the creators' id
communityId: id of the community that meeting is tied to
startTime: 22/08/2015 08:00
location: HongKong or irc address
duration: 2 hours
attendants: ids of users
agenda: text describing the meeting content

Return:
success or fail

**Comment by emredmrl** [comment]
Hi @hasancanakgunduz 

/api/meetings/{communityId}

You can use POST method to this webservice. Format your JSON accordingly.
