### ISSUE TITLE
Topic Detail Service

### ISSUE THREAD

**Issue by emregurer** [BogaziciUniversitySWEG1/web-app-repo#65]
api/topics/{topicId} method does not return user object. Just returning creatorUserId value.

**Comment by alperkaratepe** [comment]
Following params should be sent for createTopic POST message:
- title
- description
- communityId
- creatorUserId
  Example POST request:
  http://localhost:8080/api/topics?title=Topic Title&description=Topic Description&communityId=2&creatorUserId=1
