### ISSUE TITLE
Index - Sort by links are not working in index page

### ISSUE THREAD

**Issue by alperkaratepe** [BogaziciUniversitySWEG1/web-app-repo#73]
Title
Creation Date

**Comment by hasancanakgunduz** [comment]
I need a new service to implement this one. The communities service need to take one more parameter: SORT_BY_TITLE, SORT_BY_CREATION_DATE, SORT_BY_MEMBER_COUNT.

By the way what is the default behaviour of this service? Currently, what is the criteria to sort?

**Comment by alperkaratepe** [comment]
Implemented. Add a url parameter "sortType" into requests. 
It is optional and Its value may be SORT_BY_TITLE and SORT_BY_CREATION_DATE.
SORT_BY_MEMBER_COUNT could not be added because communities table does not have a membercount field. It may be done in javascript. Tha class have a membercount field.

**Comment by hasancanakgunduz** [comment]
Remaining work to be done with #171
