### ISSUE TITLE
Index - Search community does not work

### ISSUE THREAD

**Issue by emregurer** [BogaziciUniversitySWEG1/web-app-repo#99]

**Comment by hasancanakgunduz** [comment]
Enhancement Name: Searching communites function on index page should be implemented
Build Number: Build taken on 20 Dec 2015, 17:09
Severity: Medium
Priority: Medium
Environment: Google Chrome / Mac OSX

Steps To Reproduce:
1) Open http://localhost:8080/index.html
2) Click on search field
3) Enter keyword
4) Click on search button or enter button

Expected result: Communities section is updated with results

**Comment by emregurer** [comment]
completed.
